- name: apt-install
  hosts: all
  become: true
  vars:
    container_count: 1
    user: wischmcj
    default_container_image: ubuntu
    default_container_command: sleep 1d
  tasks:

    - name: Add {{ user }} to 'sudo'
      ansible.builtin.user:
        name: "{{ user }}"
        groups: sudo
        state: present

    - name: Add SSH key to user
      ansible.posix.authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', pub_key) }}"

    - name: Wait for apt to unlock
      become: true
      ansible.builtin.shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - ffmpeg
          - libsm6
          - libxext6
        state: latest
        update_cache: true

    - name: Wait for apt to unlock
      become: true
      ansible.builtin.shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Add DO agent apt key
      ansible.builtin.apt_key:
        url: https://repos.insights.digitalocean.com/sonar-agent.asc
        state: present

    - name: Add DO agent repository
      ansible.builtin.apt_repository:
        repo: deb https://repos.insights.digitalocean.com/apt/do-agent main main
        filename: digitalocean-agent
        state: present

    - name: Install DO agent
      ansible.builtin.apt:
        pkg: do-agent
        state: present
